/**
 * Generates and writes the shell env bootstrap script for a launchd agent.
 *
 * The script is sourced by the plist shell command before the agent process
 * starts, so all settings env vars and agent repo assignments are available
 * in process.env without needing the chatbot to pass them at spawn time.
 *
 * - Plain vars: inlined as `export KEY='value'`
 * - Secret vars: fetched at runtime via `security find-generic-password`
 * - Repo assignments: inlined as `export REPOS_VAR='slug1,slug2'`
 */

import { writeFile } from "node:fs/promises";
import { agentEnvScript } from "./paths";

export interface EnvScriptVar {
  key: string;
  value: string;
  isSecret: boolean;
  keychainService?: string;
  keychainAccount?: string;
}

export interface EnvScriptSettings {
  repositories: Array<{ id: string; githubRepo: string }>;
  envVars: EnvScriptVar[];
}

/** Single-quote a shell value, escaping any embedded single quotes. */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

function generateEnvScript(
  envVars: EnvScriptVar[],
  reposEnvVar: string | undefined,
  repoSlugs: string[],
): string {
  const lines: string[] = [
    "# Auto-generated by dovepaw — do not edit manually.",
    "# Sourced by launchd before the agent process starts.",
    "",
  ];

  for (const v of envVars) {
    if (v.isSecret) {
      const service = v.keychainService ?? "dovepaw";
      const account = v.keychainAccount ?? v.key;
      lines.push(
        `export ${v.key}=$(security find-generic-password -s ${shellQuote(service)} -a ${shellQuote(account)} -w 2>/dev/null)`,
      );
    } else if (v.value !== "") {
      lines.push(`export ${v.key}=${shellQuote(v.value)}`);
    }
  }

  if (reposEnvVar && repoSlugs.length > 0) {
    lines.push(`export ${reposEnvVar}=${shellQuote(repoSlugs.join(","))}`);
  }

  return lines.join("\n") + "\n";
}

/**
 * Resolves repo slugs from settings, generates the env script, and writes it
 * to ~/.claude/scheduler/<agentName>.env.sh (mode 0700).
 */
export async function writeAgentEnvScript(
  agentName: string,
  reposEnvVar: string | undefined,
  settings: EnvScriptSettings,
  agentRepoIds: string[],
): Promise<void> {
  const repoSlugs = agentRepoIds
    .map((id) => settings.repositories.find((r) => r.id === id))
    .filter((r): r is NonNullable<typeof r> => r !== undefined)
    .map((r) => r.githubRepo);
  const content = generateEnvScript(settings.envVars, reposEnvVar, repoSlugs);
  await writeFile(agentEnvScript(agentName), content, { mode: 0o700 });
}
