import { describe, expect, it, afterEach } from "vitest";
import { writeAgentEnvScript, type EnvScriptSettings } from "./env-script.js";
import { existsSync, readFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const TMP_AGENT = `__test_env_script_${process.pid}`;

function readTmpScript(): string {
  return readFileSync(join(process.env.HOME!, `.claude/scheduler/${TMP_AGENT}.env.sh`), "utf-8");
}

function cleanupTmpScript(): void {
  const path = join(process.env.HOME!, `.claude/scheduler/${TMP_AGENT}.env.sh`);
  if (existsSync(path)) unlinkSync(path);
}

const SETTINGS: EnvScriptSettings = {
  repositories: [
    { id: "r1", githubRepo: "org/repo-one" },
    { id: "r2", githubRepo: "org/repo-two" },
  ],
  envVars: [
    { key: "PLAIN_VAR", value: "hello world", isSecret: false },
    { key: "EMPTY_VAR", value: "", isSecret: false },
    {
      key: "SECRET_VAR",
      value: "",
      isSecret: true,
      keychainService: "my-service",
      keychainAccount: "my-account",
    },
    { key: "DOVEPAW_SECRET", value: "", isSecret: true },
  ],
};

describe("writeAgentEnvScript", () => {
  afterEach(cleanupTmpScript);

  it("exports plain vars inline", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, []);
    expect(readTmpScript()).toContain("export PLAIN_VAR='hello world'");
  });

  it("skips empty plain vars", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, []);
    expect(readTmpScript()).not.toContain("EMPTY_VAR");
  });

  it("emits security find-generic-password for secrets with explicit keychain coords", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, []);
    expect(readTmpScript()).toContain(
      "export SECRET_VAR=$(security find-generic-password -s 'my-service' -a 'my-account' -w 2>/dev/null)",
    );
  });

  it("defaults to dovepaw service and key name as account for managed secrets", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, []);
    expect(readTmpScript()).toContain(
      "export DOVEPAW_SECRET=$(security find-generic-password -s 'dovepaw' -a 'DOVEPAW_SECRET' -w 2>/dev/null)",
    );
  });

  it("exports repo slugs under reposEnvVar when agent repos are set", async () => {
    await writeAgentEnvScript(TMP_AGENT, "AGENT_REPOS", SETTINGS, ["r1", "r2"]);
    expect(readTmpScript()).toContain("export AGENT_REPOS='org/repo-one,org/repo-two'");
  });

  it("omits reposEnvVar line when no repos are assigned", async () => {
    await writeAgentEnvScript(TMP_AGENT, "AGENT_REPOS", SETTINGS, []);
    expect(readTmpScript()).not.toContain("AGENT_REPOS");
  });

  it("omits reposEnvVar line when reposEnvVar is undefined", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, ["r1"]);
    expect(readTmpScript()).not.toContain("org/repo-one");
  });

  it("skips unknown repo IDs", async () => {
    await writeAgentEnvScript(TMP_AGENT, "AGENT_REPOS", SETTINGS, ["r1", "unknown-id"]);
    expect(readTmpScript()).toContain("export AGENT_REPOS='org/repo-one'");
  });

  it("single-quote-escapes values containing single quotes", async () => {
    const settings: EnvScriptSettings = {
      repositories: [],
      envVars: [{ key: "TRICKY", value: "it's alive", isSecret: false }],
    };
    await writeAgentEnvScript(TMP_AGENT, undefined, settings, []);
    expect(readTmpScript()).toContain("export TRICKY='it'\\''s alive'");
  });

  it("includes the auto-generated header", async () => {
    await writeAgentEnvScript(TMP_AGENT, undefined, SETTINGS, []);
    expect(readTmpScript()).toContain("Auto-generated by dovepaw");
  });
});
