/**
 * OpenViking memory provider.
 *
 * Routes every group's moments through a `viking://agent/<contextId>/moments`
 * namespace on the OpenViking sidecar. The sidecar is started externally
 * (by Electron or scripts/boot-openviking.ts) — this class only owns the
 * HTTP API calls and the in-process provider lifecycle.
 *
 * Per-group bootstrap (instance `initGroup()`):
 *   POST /api/v1/fs/mkdir viking://agent/<id>/moments
 *
 * If anything in the boot path fails, callers fall back to MarkdownMemoryProvider
 * (see `getMemoryProvider()` registry).
 */

import { type ChildProcess } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { bootOpenViking } from "@@/lib/openviking-spawner";
import type { MemoryProvider } from "./types";
import { indentedMomentsPattern, rosterBullet } from "./types";
import { KILL_ESCALATION_MS } from "@@/lib/process-constants";

export class OpenVikingMemoryProvider implements MemoryProvider {
  /** Port the sidecar process is reachable on. */
  readonly port: number;
  /** Child process handle so callers can SIGTERM on shutdown. */
  readonly proc: ChildProcess | null;

  constructor(port: number, proc: ChildProcess | null = null) {
    this.port = port;
    this.proc = proc;
  }

  /**
   * Boot the OpenViking sidecar in localhost-only dev mode and return a
   * fully-provisioned provider. Rejects on spawn or health-probe failure.
   * Used only when the sidecar has not been started externally (no port file).
   */
  static async boot(port: number): Promise<OpenVikingMemoryProvider> {
    const proc = await bootOpenViking(port);
    return new OpenVikingMemoryProvider(port, proc);
  }

  /**
   * Gracefully terminate the sidecar and wait for it to actually exit so the
   * data-directory file lock is released before any caller tries to spawn a
   * replacement. SIGTERM first, then SIGKILL as a backstop after
   * KILL_ESCALATION_MS.
   */
  async shutdown(): Promise<void> {
    const proc = this.proc;
    if (!proc) return;
    if (proc.exitCode !== null || proc.signalCode !== null) return;

    const exited = new Promise<void>((resolve) => {
      proc.once("exit", () => resolve());
    });
    try {
      proc.kill("SIGTERM");
    } catch {}
    const sigkillTimer = setTimeout(() => {
      try {
        proc.kill("SIGKILL");
      } catch {}
    }, KILL_ESCALATION_MS);
    try {
      await exited;
    } finally {
      clearTimeout(sigkillTimer);
    }
  }

  async init(contextId: string, _workspacePath: string): Promise<void> {
    await ensureNamespace(this.port, contextId);
  }

  async delete(contextId: string, _workspacePath: string): Promise<void> {
    await removeNamespace(this.port, contextId);
  }

  async buildReadReminder(workspacePath: string, contextId: string): Promise<string> {
    await writeMemoryScript(this.port, contextId, workspacePath);
    return `- You MUST query past moments before acting. This is a hard requirement — do not skip it:
\`\`\`
bash ${workspacePath}/memory.sh read <topic>
\`\`\``;
  }

  rosterReadReminder(workspacePath: string): string {
    return `You are participating in a group task. Before starting:\n${rosterBullet(workspacePath)}`;
  }

  buildSaveReminder(workspacePath: string): string {
    return `You MUST save moments (decisions, artifacts, insights) — this is a hard requirement, do not skip it:
\`\`\`
bash ${workspacePath}/memory.sh save <name> "<moment>"
\`\`\`
  Writing style:
${indentedMomentsPattern()}`;
  }
}

// ─── Workspace memory script ──────────────────────────────────────────────────

async function writeMemoryScript(
  port: number,
  contextId: string,
  workspacePath: string,
): Promise<void> {
  const base = `http://localhost:${port}`;
  const script = `#!/usr/bin/env bash
# Generated by DovePaw — do not edit
BASE="${base}"
AGENT_ID="${contextId}"
CMD="\${1:-read}"
shift

case "$CMD" in
  read)
    python3 -c "import json,sys; print(json.dumps({'query':sys.argv[1],'target_uri':'viking://agent/memories','limit':10}))" "\${*:-memories}" | \\
    curl -sX POST "\${BASE}/api/v1/search/find" \\
      -H "X-OpenViking-Agent: \${AGENT_ID}" \\
      -H "Content-Type: application/json" \\
      -d @-
    ;;
  save)
    SID=$(curl -sX POST "\${BASE}/api/v1/sessions" \\
      -H "X-OpenViking-Agent: \${AGENT_ID}" \\
      -H "Content-Type: application/json" \\
      -d '{}' | python3 -c "import sys,json; print(json.load(sys.stdin)['result']['session_id'])")
    python3 -c "import json,sys; print(json.dumps({'role':'user','content':sys.argv[1]}))" "\${*}" | \\
    curl -sX POST "\${BASE}/api/v1/sessions/\${SID}/messages" \\
      -H "X-OpenViking-Agent: \${AGENT_ID}" \\
      -H "Content-Type: application/json" \\
      -d @-
    curl -sX POST "\${BASE}/api/v1/sessions/\${SID}/commit" \\
      -H "X-OpenViking-Agent: \${AGENT_ID}" \\
      -H "Content-Type: application/json" \\
      -d '{}'
    ;;
esac
`;
  await writeFile(join(workspacePath, "memory.sh"), script, { mode: 0o755 });
}

// ─── HTTP API helpers ─────────────────────────────────────────────────────────

async function ensureNamespace(port: number, contextId: string): Promise<void> {
  const uri = `viking://agent/${contextId}/memories`;
  const response = await fetch(`http://localhost:${port}/api/v1/fs/mkdir`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-OpenViking-Agent": contextId,
    },
    body: JSON.stringify({ uri }),
  });
  const bodySchema = z.object({
    status: z.string().optional(),
    error: z.object({ code: z.string().optional(), message: z.string().optional() }).nullish(),
  });
  const raw: unknown = await response.json().catch(() => undefined);
  const body = bodySchema.safeParse(raw).data;
  if (response.ok && body?.status === "ok") return;
  if (body?.error?.code === "ALREADY_EXISTS") return;
  const message = body?.error?.message ?? `HTTP ${response.status}`;
  throw new Error(`POST /api/v1/fs/mkdir ${uri} failed: ${message}`);
}

async function removeNamespace(port: number, contextId: string): Promise<void> {
  try {
    const uri = encodeURIComponent(`viking://agent/${contextId}`);
    await fetch(`http://localhost:${port}/api/v1/fs?uri=${uri}&recursive=true`, {
      method: "DELETE",
      headers: { "X-OpenViking-Agent": contextId },
    });
  } catch {
    // sidecar unreachable — drop silently
  }
}
